// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtUnnOAHH3fDffZKK_EhqOrt4vomOiHFo',
    appId: '1:107894141193:web:9c5eb0c13effa97964a3d8',
    messagingSenderId: '107894141193',
    projectId: 'crave-4360',
    authDomain: 'crave-4360.firebaseapp.com',
    storageBucket: 'crave-4360.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEM0ZluyqIjQP5b-5UJufNEMvogur26HQ',
    appId: '1:107894141193:android:e48deca0c9a26f0b64a3d8',
    messagingSenderId: '107894141193',
    projectId: 'crave-4360',
    storageBucket: 'crave-4360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpWkFaOhenuChyElXdSk3q3SH3wkn-e8',
    appId: '1:107894141193:ios:90a80fc8d03fa3f264a3d8',
    messagingSenderId: '107894141193',
    projectId: 'crave-4360',
    storageBucket: 'crave-4360.appspot.com',
    iosClientId: '107894141193-01cirhb0b76pqldj51quunkvrnqumb6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.crave4360',
  );
}
